services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: movie_ai_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: movie_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
